# Generated by Django 6.0.3 on 2026-03-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("players", models.CharField(max_length=50)),
                ("play_time", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
